version: '2'
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    network_mode: host
    environment:
      LANG: en_US.utf8
      LC_ALL: en_US.utf8
    volumes:
      - "/root/docker/nginx/html:/usr/share/nginx/html"
      - "/root/docker/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "/root/docker/nginx/ssl:/etc/nginx/ssl"
      - "/root/docker/nginx/conf.d:/etc/nginx/conf.d"
      - "/root/docker/nginx/log:/var/log/nginx"
